server:
  service:
    type: NodePort
    nodePort: 30090  # Optional: Change or remove if you want random port
    port: 9090

alertmanager:
  service:
    type: NodePort
    nodePort: 30093  # Optional: Change or remove if you want random port
    port: 9093

serverFiles:
  alerting_rules.yml:
    groups:
    - name: NodeDown
      rules:
      - alert: InstanceDown
        expr: up{job="kubernetes-nodes"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          host: "{{ $labels.kubernetes_io_hostname }}"
          summary: "Instance down"
          description: "Node {{ $labels.kubernetes_io_hostname }} has been down for more than 2 minutes."

    - name: node_resource_alerts
      rules:
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 70
        for: 2m
        labels:
          severity: warning
        annotations:
          host: "{{ $labels.kubernetes_node }}"
          summary: "{{ $labels.kubernetes_node }} memory usage is high: {{ printf \"%.2f\" $value }}%"
          description: "Node {{ $labels.kubernetes_node }} is using more than 70% memory."

      - alert: HighCPUUsage
        expr: (1 - avg(rate(node_cpu_seconds_total{mode="idle"}[5m])) by (instance)) * 100 > 70
        for: 2m
        labels:
          severity: warning
        annotations:
          host: "{{ $labels.kubernetes_node }}"
          summary: "{{ $labels.kubernetes_node }} CPU usage is high: {{ printf \"%.2f\" $value }}%"
          description: "Node {{ $labels.kubernetes_node }} is using more than 70% CPU."

    - name: pod_alerts
      rules:
      - alert: KubePodCrashLooping
        expr: rate(kube_pod_container_status_restarts_total{job="kubernetes-service-endpoints",namespace=~".*"}[5m]) * 60 * 5 > 0
        for: 2m
        labels:
          severity: warning
        annotations:
          description: Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container }}) is restarting {{ printf "%.2f" $value }} times / 5 minutes.
          summary: Pod is crash looping for more than 2 minutes.

      - alert: KubePodNotReady
        expr: sum by(namespace, pod) (
                max by(namespace, pod) (kube_pod_status_phase{job="kubernetes-service-endpoints",namespace=~".*",phase=~"Pending|Unknown"})
                * on(namespace, pod) group_left(owner_kind)
                topk by(namespace, pod) (1, max by(namespace, pod, owner_kind) (kube_pod_owner{owner_kind!="Job"}))
              ) > 0
        for: 2m
        labels:
          severity: warning
        annotations:
          description: Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a non-ready state for longer than 2 minutes.
          summary: Pod has been in a non-ready state for more than 2 minutes.
