apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-server
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi   # Change size if needed
  storageClassName: "local-path" # Use default storage class or specify if you have one
